version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - $DB_HOST:$DB_PORT:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: test

volumes:
  mysql_data:
